=== DawidWIld/SEMIII/XML/incidents.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" 
           xmlns:xs = "http://www.w3.org/2001/XMLSchema"
           xmlns:inc = "http://project/incidents.xsd">

  <xs:simpleType name="phoneNumberType">
    <xs:restriction base="xs:string">
      <xs:maxLength value="18" />
      <xs:pattern value="\+?[0-9]+" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="authors" />
        <xs:element ref="companies" />
        <xs:element ref="incidents" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="authors">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" name="author">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="firstName" type="xs:string" />
              <xs:element name="lastName" type="xs:string" />
              <xs:element name="indexNumber" type="xs:nonNegativeInteger" />
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="companies">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="company">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute name="id" type="xs:ID" use="required" />
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element> 

  <xs:element name="incidents">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="incident" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="incident">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="incidentID" type="xs:string" />
        <xs:element name="endUser" type="xs:string" />
        <xs:element name="dateOpened" type="xs:date" />
        <xs:element name="affectedUsers" type="xs:string" />
        <xs:element name="state" type="xs:string" />
        <xs:element name="category">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="mainCategory" type="xs:string" />
              <xs:element name="subcategory" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="priority">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="impact">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="Low" />
                    <xs:enumeration value="Medium" />
                    <xs:enumeration value="High" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="urgency">
                <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:minInclusive value="0" />
                    <xs:maxInclusive value="5" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="assignmentGroup" type="xs:string" />
        <xs:element ref="phoneNumber" />
        <xs:element name="userCompany">
          <xs:complexType>
            <xs:attribute name="comid" type="xs:IDREF" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="shortDescription" type="xs:string" />
        <xs:element name="description" type="xs:string" />
        <xs:element ref="workNotes" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="phoneNumber">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="phoneNumberType">
          <xs:attribute name="cc" type="xs:language" use="required" />
          <xs:attribute name="mobile" type="xs:boolean" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="workNotes">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="vis" use="required">
            <xs:simpleType>
              <xs:restriction base="xs:NMTOKEN">
                <xs:enumeration value="agentOnly" />
                <xs:enumeration value="all" />
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== DawidWIld/SEMIII/XML/incidents.xml
<?xml version="1.0" encoding="UTF-8"?>

<root xmlns="http://project/incidents.xsd"
      xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
      xsi:schemaLocation='http://project/companies.xsd companies.xsd
      http://project/incidents.xsd incidents.xsd
      http://project/authors.xsd authors.xsd'>

  <aut:authors xmlns:aut="http://project/authors.xsd">
    <aut:author id="A1">
      <aut:firstName>Mateusz</aut:firstName>
      <aut:lastName>Muszy≈Ñski</aut:lastName>
      <aut:indexNumber>217120</aut:indexNumber>
    </aut:author>
    <aut:author id="A2">
      <aut:firstName>Dawid</aut:firstName>
      <aut:lastName>Dziki</aut:lastName>
      <aut:indexNumber>217088</aut:indexNumber>
    </aut:author>
  </aut:authors>

  <comp:companies xmlns:comp="http://project/companies.xsd">
    <comp:company id="DDMT00001">Nazwa firmy</comp:company>
    <comp:company id="DDMT00002">Nazwa firmy 2</comp:company>
  </comp:companies>

  <incidents>
    <incident>
      <incidentID>INC000001</incidentID>
      <endUser>Kason Wilcox</endUser>
      <dateOpened>2018-10-01</dateOpened>
      <affectedUsers>single user</affectedUsers>
      <state>New</state>
      <category>
        <mainCategory>Hardware</mainCategory>
        <subcategory>Workstation</subcategory>
      </category>
      <priority>
        <impact>Medium</impact>
        <urgency>2</urgency>
      </priority>
      <assignmentGroup>Local Support</assignmentGroup>
      <phoneNumber cc="PL" mobile="true">+48577552017</phoneNumber>
      <userCompany comid="DDMT00001"></userCompany>
      <shortDescription>I have an issue with my Workstation</shortDescription>
      <description>Modi sit magnam dolor dolorem ipsum labore. Ipsum velit dolorem numquam numquam. Quisquam voluptatem est neque. Tempora ut voluptatem eius consectetur. Ipsum ipsum sit sit sit voluptatem numquam.</description>
      <workNotes vis="agentOnly">Velit etincidunt labore non quiquia adipisci.</workNotes>
    </incident>

    <incident>
      <incidentID>INC000002</incidentID>
      <endUser>Aurora Mason</endUser>
      <dateOpened>2018-10-02</dateOpened>
      <affectedUsers>single user</affectedUsers>
      <state>Resolved</state>
      <category>
        <mainCategory>Software</mainCategory>
        <subcategory>MS Office</subcategory>
      </category>
      <priority>
        <impact>Medium</impact>
        <urgency>4</urgency>
      </priority>
      <assignmentGroup>Service Desk</assignmentGroup>
      <phoneNumber cc="PL" mobile="true">+48503193056</phoneNumber>
      <userCompany comid="DDMT00002"></userCompany>
      <shortDescription>I have an issue with my MS Office</shortDescription>
      <description>Voluptatem adipisci non voluptatem quiquia dolore. Non velit dolore ipsum. Est modi tempora neque numquam quisquam. Non tempora sit sed aliquam non dolor aliquam. Tempora quisquam ut non amet tempora magnam consectetur. Labore etincidunt quaerat sit adipisci voluptatem non dolorem. Adipisci ipsum labore non porro amet adipisci.</description>
      <workNotes vis="agentOnly">Amet quaerat est consectetur.</workNotes>
    </incident>

    <incident>
      <incidentID>INC000003</incidentID>
      <endUser>Allen Collins</endUser>
      <dateOpened>2018-10-03</dateOpened>
      <affectedUsers>&gt;70%</affectedUsers>
      <state>Resolved</state>
      <category>
        <mainCategory>Identity Management</mainCategory>
        <subcategory>Password Reset</subcategory>
      </category>
      <priority>
        <impact>Medium</impact>
        <urgency>1</urgency>
      </priority>
      <assignmentGroup>Service Desk</assignmentGroup>
      <phoneNumber cc="PL" mobile="true">+48566950815</phoneNumber>
      <userCompany comid="DDMT00002"></userCompany>
      <shortDescription>I have an issue with my Password Reset</shortDescription>
      <description>Ipsum aliquam sed velit. Numquam dolorem etincidunt magnam ipsum dolorem modi velit. Sit dolorem quiquia tempora quiquia eius porro etincidunt. Magnam dolor porro dolore ut numquam dolor. Quiquia est adipisci tempora tempora modi.</description>
      <workNotes vis="agentOnly">Numquam consectetur voluptatem amet quisquam quaerat.</workNotes>
    </incident>

    <incident>
      <incidentID>INC000004</incidentID>
      <endUser>Fernanda Davis</endUser>
      <dateOpened>2018-10-04</dateOpened>
      <affectedUsers>&gt;70%</affectedUsers>
      <state>Work in progress</state>
      <category>
        <mainCategory>Identity Management</mainCategory>
        <subcategory>Password Reset</subcategory>
      </category>
      <priority>
        <impact>High</impact>
        <urgency>4</urgency>
      </priority>
      <assignmentGroup>Service Desk</assignmentGroup>
      <phoneNumber cc="PL" mobile="true">+48582123402</phoneNumber>
      <userCompany comid="DDMT00001"></userCompany>
      <shortDescription>I have an issue with my Password Reset</shortDescription>
      <description>Dolor quiquia eius dolore sed. Consectetur eius quaerat quiquia quisquam. Consectetur quiquia ut quisquam adipisci. Eius eius non est labore quiquia sit non. Quisquam dolore quiquia dolor aliquam. Amet amet labore dolor dolor tempora magnam.</description>
      <workNotes vis="agentOnly">Amet aliquam non sed.</workNotes>
    </incident>

    <incident>
      <incidentID>INC000005</incidentID>
      <endUser>Philip Strong</endUser>
      <dateOpened>2018-10-05</dateOpened>
      <affectedUsers>40% - 70%</affectedUsers>
      <state>New</state>
      <category>
        <mainCategory>Hardware</mainCategory>
        <subcategory>Laptop</subcategory>
      </category>
      <priority>
        <impact>High</impact>
        <urgency>3</urgency>
      </priority>
      <assignmentGroup>Local Support</assignmentGroup>
      <phoneNumber cc="PL" mobile="true">+48573412519</phoneNumber>
      <userCompany comid="DDMT00001"></userCompany>
      <shortDescription>I have an issue with my Laptop</shortDescription>
      <description>Numquam dolor quiquia ut etincidunt consectetur ipsum labore. Quaerat amet ut tempora est. Sed etincidunt amet quiquia. Magnam dolor numquam amet eius aliquam. Porro quaerat dolorem est dolore labore dolore. Sit consectetur numquam tempora sed velit. Numquam est ipsum quiquia. Quaerat ut modi amet sit magnam porro.</description>
      <workNotes vis="agentOnly">Quaerat tempora magnam adipisci tempora quisquam neque numquam.</workNotes>
    </incident>

    <incident>
      <incidentID>INC000006</incidentID>
      <endUser>Jazmyn Buchanan</endUser>
      <dateOpened>2018-10-06</dateOpened>
      <affectedUsers>&lt;40%</affectedUsers>
      <state>Awaiting info</state>
      <category>
        <mainCategory>Identity Management</mainCategory>
        <subcategory>Account Lockout</subcategory>
      </category>
      <priority>
        <impact>High</impact>
        <urgency>1</urgency>
      </priority>
      <assignmentGroup>Service Desk</assignmentGroup>
      <phoneNumber cc="PL" mobile="true">+48526815231</phoneNumber>
      <userCompany comid="DDMT00001"></userCompany>
      <shortDescription>I have an issue with my Account Lockout</shortDescription>
      <description>Quisquam est tempora labore. Dolor sit dolorem numquam dolor est etincidunt quiquia. Sit ut etincidunt adipisci ipsum amet. Tempora tempora neque sed. Magnam sed tempora neque numquam. Est magnam tempora tempora est. Magnam sed velit dolore etincidunt quiquia voluptatem.</description>
      <workNotes vis="agentOnly">Etincidunt ut magnam eius eius.</workNotes>
    </incident>

    <incident>
      <incidentID>INC000007</incidentID>
      <endUser>Bryan Dorsey</endUser>
      <dateOpened>2018-10-07</dateOpened>
      <affectedUsers>&lt;40%</affectedUsers>
      <state>Awaiting info</state>
      <category>
        <mainCategory>Software</mainCategory>
        <subcategory>Browser</subcategory>
      </category>
      <priority>
        <impact>Low</impact>
        <urgency>4</urgency>
      </priority>
      <assignmentGroup>Service Desk</assignmentGroup>
      <phoneNumber cc="PL" mobile="true">+48577221774</phoneNumber>
      <userCompany comid="DDMT00001"></userCompany>
      <shortDescription>I have an issue with my Browser</shortDescription>
      <description>Magnam ipsum numquam adipisci non sed. Etincidunt sit dolore porro consectetur magnam. Ut sit porro voluptatem etincidunt. Eius adipisci est magnam etincidunt consectetur porro. Sed amet adipisci dolor.</description>
      <workNotes vis="agentOnly">Quaerat tempora quaerat quiquia dolore sed.</workNotes>
    </incident>

    <incident>
      <incidentID>INC000008</incidentID>
      <endUser>Blaze Wolfe</endUser>
      <dateOpened>2018-10-08</dateOpened>
      <affectedUsers>single user</affectedUsers>
      <state>Work in progress</state>
      <category>
        <mainCategory>Identity Management</mainCategory>
        <subcategory>Password Reset</subcategory>
      </category>
      <priority>
        <impact>High</impact>
        <urgency>2</urgency>
      </priority>
      <assignmentGroup>Service Desk</assignmentGroup>
      <phoneNumber cc="PL" mobile="true">+48507779857</phoneNumber>
      <userCompany comid="DDMT00001"></userCompany>
      <shortDescription>I have an issue with my Password Reset</shortDescription>
      <description>Ut numquam sit amet consectetur sit dolor. Consectetur amet dolore etincidunt adipisci. Consectetur ipsum quaerat consectetur. Ut est quaerat ipsum magnam. Voluptatem est non velit quiquia. Voluptatem porro consectetur velit tempora sit numquam.</description>
      <workNotes vis="agentOnly">Voluptatem ipsum labore ipsum.</workNotes>
    </incident>

    <incident>
      <incidentID>INC000009</incidentID>
      <endUser>Avery Mcmillan</endUser>
      <dateOpened>2018-10-09</dateOpened>
      <affectedUsers>single user</affectedUsers>
      <state>Work in progress</state>
      <category>
        <mainCategory>Software</mainCategory>
        <subcategory>Browser</subcategory>
